# auto_subliminal/config.py
# Configuration specific to the Auto Subliminal Generation feature

# --- Affirmation Generation ---
# Default number of initial affirmations to generate from the topic before main expansion
AUTO_SUB_DEFAULT_INITIAL_AFFIRMATIONS = 7  # Number of affirmations from topic_keywords generator

# Multiplier for the main expansion step (passed to affirmation_expander.expand_affirmations)
AUTO_SUB_MAIN_EXPANSION_MULTIPLIER = 2  # How much to expand the initial set

# --- Audio Mixing ---
# Default volume level for affirmations relative to background (e.g., -20 dBFS for very subtle)
# This will be used by the actual audio mixer.
AUTO_SUB_AFFIRMATION_VOLUME_DB_OFFSET = -20.0  # Quieter than background

# --- Preview ---
# Duration for the preview audio generated by the auto feature (in seconds)
AUTO_SUB_PREVIEW_DURATION_S = 10

# --- Output ---
# Subdirectory within the main application's output directory for files from this feature
AUTO_SUB_OUTPUT_SUBDIR = "auto_generated_subliminals"

# Default audio format for raw affirmations (e.g., wav for quality, mp3 for size)
AUTO_SUB_RAW_AFFIRMATIONS_FORMAT = "wav"

# Default audio format for the final mixed subliminal (e.g., mp3 for distribution)
AUTO_SUB_FINAL_SUBLIMINAL_FORMAT = "mp3"
